theme: jekyll-theme-cayman
body: <a target="_blank" href="https://calendar.google.com/event?action=TEMPLATE&amp;tmeid=M3Nta2FnN2dkbXFvZHJzc2FmMzRiMjA4cTUgbmF6YXJrYXZrYTExQG0&amp;tmsrc=nazarkavka11%40gmail.com"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_uk.gif"></a>
